Collections:
  - Name: encnet
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: encnet_r50-d8_512x1024_40k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 218.34
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.67
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r50-d8_512x1024_40k_cityscapes/encnet_r50-d8_512x1024_40k_cityscapes_20200621_220958-68638a47.pth
    Config: configs/encnet/encnet_r50-d8_512x1024_40k_cityscapes.py



  - Name: encnet_r101-d8_512x1024_40k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 375.94
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.81
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r101-d8_512x1024_40k_cityscapes/encnet_r101-d8_512x1024_40k_cityscapes_20200621_220933-35e0a3e8.pth
    Config: configs/encnet/encnet_r101-d8_512x1024_40k_cityscapes.py



  - Name: encnet_r50-d8_769x769_40k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 549.45
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.24
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r50-d8_769x769_40k_cityscapes/encnet_r50-d8_769x769_40k_cityscapes_20200621_220958-3bcd2884.pth
    Config: configs/encnet/encnet_r50-d8_769x769_40k_cityscapes.py



  - Name: encnet_r101-d8_769x769_40k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 793.65
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 74.25
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r101-d8_769x769_40k_cityscapes/encnet_r101-d8_769x769_40k_cityscapes_20200621_220933-2fafed55.pth
    Config: configs/encnet/encnet_r101-d8_769x769_40k_cityscapes.py



  - Name: encnet_r50-d8_512x1024_80k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 218.34
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.94
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r50-d8_512x1024_80k_cityscapes/encnet_r50-d8_512x1024_80k_cityscapes_20200622_003554-fc5c5624.pth
    Config: configs/encnet/encnet_r50-d8_512x1024_80k_cityscapes.py



  - Name: encnet_r101-d8_512x1024_80k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 375.94
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.55
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r101-d8_512x1024_80k_cityscapes/encnet_r101-d8_512x1024_80k_cityscapes_20200622_003555-1de64bec.pth
    Config: configs/encnet/encnet_r101-d8_512x1024_80k_cityscapes.py



  - Name: encnet_r50-d8_769x769_80k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 549.45
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.44
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r50-d8_769x769_80k_cityscapes/encnet_r50-d8_769x769_80k_cityscapes_20200622_003554-55096dcb.pth
    Config: configs/encnet/encnet_r50-d8_769x769_80k_cityscapes.py



  - Name: encnet_r101-d8_769x769_80k_cityscapes
    In Collection: encnet
    Metadata:
      inference time (ms/im): 793.65
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.10
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r101-d8_769x769_80k_cityscapes/encnet_r101-d8_769x769_80k_cityscapes_20200622_003555-470ef79d.pth
    Config: configs/encnet/encnet_r101-d8_769x769_80k_cityscapes.py



  - Name: encnet_r50-d8_512x512_80k_ade20k
    In Collection: encnet
    Metadata:
      inference time (ms/im): 43.84
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 39.53
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r50-d8_512x512_80k_ade20k/encnet_r50-d8_512x512_80k_ade20k_20200622_042412-44b46b04.pth
    Config: configs/encnet/encnet_r50-d8_512x512_80k_ade20k.py



  - Name: encnet_r101-d8_512x512_80k_ade20k
    In Collection: encnet
    Metadata:
      inference time (ms/im): 67.25
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.11
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r101-d8_512x512_80k_ade20k/encnet_r101-d8_512x512_80k_ade20k_20200622_101128-dd35e237.pth
    Config: configs/encnet/encnet_r101-d8_512x512_80k_ade20k.py



  - Name: encnet_r50-d8_512x512_160k_ade20k
    In Collection: encnet
    Metadata:
      inference time (ms/im): 43.84
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 40.10
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r50-d8_512x512_160k_ade20k/encnet_r50-d8_512x512_160k_ade20k_20200622_101059-b2db95e0.pth
    Config: configs/encnet/encnet_r50-d8_512x512_160k_ade20k.py



  - Name: encnet_r101-d8_512x512_160k_ade20k
    In Collection: encnet
    Metadata:
      inference time (ms/im): 67.25
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.61
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/encnet/encnet_r101-d8_512x512_160k_ade20k/encnet_r101-d8_512x512_160k_ade20k_20200622_073348-7989641f.pth
    Config: configs/encnet/encnet_r101-d8_512x512_160k_ade20k.py
