Collections:
  - Name: NonLocal
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: nonlocal_r50-d8_512x1024_40k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 367.65
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.24
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_512x1024_40k_cityscapes/nonlocal_r50-d8_512x1024_40k_cityscapes_20200605_210748-c75e81e3.pth
    Config: configs/nonlocal/nonlocal_r50-d8_512x1024_40k_cityscapes.py



  - Name: nonlocal_r101-d8_512x1024_40k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 512.82
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.66
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x1024_40k_cityscapes/nonlocal_r101-d8_512x1024_40k_cityscapes_20200605_210748-d63729fa.pth
    Config: configs/nonlocal/nonlocal_r101-d8_512x1024_40k_cityscapes.py



  - Name: nonlocal_r50-d8_769x769_40k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 657.89
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.33
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_769x769_40k_cityscapes/nonlocal_r50-d8_769x769_40k_cityscapes_20200530_045243-82ef6749.pth
    Config: configs/nonlocal/nonlocal_r50-d8_769x769_40k_cityscapes.py



  - Name: nonlocal_r101-d8_769x769_40k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 952.38
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.57
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_769x769_40k_cityscapes/nonlocal_r101-d8_769x769_40k_cityscapes_20200530_045348-8fe9a9dc.pth
    Config: configs/nonlocal/nonlocal_r101-d8_769x769_40k_cityscapes.py



  - Name: nonlocal_r50-d8_512x1024_80k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 367.65
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.01
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_512x1024_80k_cityscapes/nonlocal_r50-d8_512x1024_80k_cityscapes_20200607_193518-d6839fae.pth
    Config: configs/nonlocal/nonlocal_r50-d8_512x1024_80k_cityscapes.py



  - Name: nonlocal_r101-d8_512x1024_80k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 512.82
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.93
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x1024_80k_cityscapes/nonlocal_r101-d8_512x1024_80k_cityscapes_20200607_183411-32700183.pth
    Config: configs/nonlocal/nonlocal_r101-d8_512x1024_80k_cityscapes.py



  - Name: nonlocal_r50-d8_769x769_80k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 657.89
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.05
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_769x769_80k_cityscapes/nonlocal_r50-d8_769x769_80k_cityscapes_20200607_193506-1f9792f6.pth
    Config: configs/nonlocal/nonlocal_r50-d8_769x769_80k_cityscapes.py



  - Name: nonlocal_r101-d8_769x769_80k_cityscapes
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 952.38
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.40
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_769x769_80k_cityscapes/nonlocal_r101-d8_769x769_80k_cityscapes_20200607_183428-0e1fa4f9.pth
    Config: configs/nonlocal/nonlocal_r101-d8_769x769_80k_cityscapes.py



  - Name: nonlocal_r50-d8_512x512_80k_ade20k
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 46.79
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 40.75
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_512x512_80k_ade20k/nonlocal_r50-d8_512x512_80k_ade20k_20200615_015801-5ae0aa33.pth
    Config: configs/nonlocal/nonlocal_r50-d8_512x512_80k_ade20k.py



  - Name: nonlocal_r101-d8_512x512_80k_ade20k
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 71.58
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.90
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x512_80k_ade20k/nonlocal_r101-d8_512x512_80k_ade20k_20200615_015758-24105919.pth
    Config: configs/nonlocal/nonlocal_r101-d8_512x512_80k_ade20k.py



  - Name: nonlocal_r50-d8_512x512_160k_ade20k
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 46.79
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.03
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_512x512_160k_ade20k/nonlocal_r50-d8_512x512_160k_ade20k_20200616_005410-baef45e3.pth
    Config: configs/nonlocal/nonlocal_r50-d8_512x512_160k_ade20k.py



  - Name: nonlocal_r101-d8_512x512_160k_ade20k
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 71.58
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 43.36
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x512_160k_ade20k/nonlocal_r101-d8_512x512_160k_ade20k_20200616_003422-affd0f8d.pth
    Config: configs/nonlocal/nonlocal_r101-d8_512x512_160k_ade20k.py



  - Name: nonlocal_r50-d8_512x512_20k_voc12aug
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 47.15
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 76.20
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_512x512_20k_voc12aug/nonlocal_r50-d8_512x512_20k_voc12aug_20200617_222613-07f2a57c.pth
    Config: configs/nonlocal/nonlocal_r50-d8_512x512_20k_voc12aug.py



  - Name: nonlocal_r101-d8_512x512_20k_voc12aug
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 71.38
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 78.15
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x512_20k_voc12aug/nonlocal_r101-d8_512x512_20k_voc12aug_20200617_222615-948c68ab.pth
    Config: configs/nonlocal/nonlocal_r101-d8_512x512_20k_voc12aug.py



  - Name: nonlocal_r50-d8_512x512_40k_voc12aug
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 47.15
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 76.65
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r50-d8_512x512_40k_voc12aug/nonlocal_r50-d8_512x512_40k_voc12aug_20200614_000028-0139d4a9.pth
    Config: configs/nonlocal/nonlocal_r50-d8_512x512_40k_voc12aug.py



  - Name: nonlocal_r101-d8_512x512_40k_voc12aug
    In Collection: NonLocal
    Metadata:
      inference time (ms/im): 71.38
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 78.27
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/nonlocal_net/nonlocal_r101-d8_512x512_40k_voc12aug/nonlocal_r101-d8_512x512_40k_voc12aug_20200614_000028-7e5ff470.pth
    Config: configs/nonlocal/nonlocal_r101-d8_512x512_40k_voc12aug.py
