Models:

  - Name: fcn_unet_s5-d16_64x64_40k_drive
    In Collection: FCN
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: DRIVE
        Metrics:
          mIoU: 0.680
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_64x64_40k_drive/fcn_unet_s5-d16_64x64_40k_drive_20201223_191051-26cee593.pth
    Config: configs/unet-s5-d16/fcn_unet_s5-d16_64x64_40k_drive.py



  - Name: pspnet_unet_s5-d16_64x64_40k_drive
    In Collection: PSPNet
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: DRIVE
        Metrics:
          mIoU: 0.599
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/pspnet_unet_s5-d16_64x64_40k_drive/pspnet_unet_s5-d16_64x64_40k_drive_20201227_181818-aac73387.pth
    Config: configs/unet-s5-d16/pspnet_unet_s5-d16_64x64_40k_drive.py



  - Name: deeplabv3_unet_s5-d16_64x64_40k_drive
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: DRIVE
        Metrics:
          mIoU: 0.596
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/deeplabv3_unet_s5-d16_64x64_40k_drive/deeplabv3_unet_s5-d16_64x64_40k_drive_20201226_094047-0671ff20.pth
    Config: configs/unet-s5-d16/deeplabv3_unet_s5-d16_64x64_40k_drive.py



  - Name: fcn_unet_s5-d16_128x128_40k_stare
    In Collection: FCN
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: STARE
        Metrics:
          mIoU: 0.968
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_128x128_40k_stare/fcn_unet_s5-d16_128x128_40k_stare_20201223_191051-6ea7cfda.pth
    Config: configs/unet-s5-d16/fcn_unet_s5-d16_128x128_40k_stare.py



  - Name: pspnet_unet_s5-d16_128x128_40k_stare
    In Collection: PSPNet
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: STARE
        Metrics:
          mIoU: 0.982
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/pspnet_unet_s5-d16_128x128_40k_stare/pspnet_unet_s5-d16_128x128_40k_stare_20201227_181818-3c2923c4.pth
    Config: configs/unet-s5-d16/pspnet_unet_s5-d16_128x128_40k_stare.py



  - Name: deeplabv3_unet_s5-d16_128x128_40k_stare
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: STARE
        Metrics:
          mIoU: 0.999
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/deeplabv3_unet_s5-d16_128x128_40k_stare/deeplabv3_unet_s5-d16_128x128_40k_stare_20201226_094047-93dcb93c.pth
    Config: configs/unet-s5-d16/deeplabv3_unet_s5-d16_128x128_40k_stare.py



  - Name: fcn_unet_s5-d16_128x128_40k_chase_db1
    In Collection: FCN
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: CHASE_DB1
        Metrics:
          mIoU: 0.968
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_128x128_40k_chase_db1/fcn_unet_s5-d16_128x128_40k_chase_db1_20201223_191051-95852f45.pth
    Config: configs/unet-s5-d16/fcn_unet_s5-d16_128x128_40k_chase_db1.py



  - Name: pspnet_unet_s5-d16_128x128_40k_chase_db1
    In Collection: PSPNet
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: CHASE_DB1
        Metrics:
          mIoU: 0.982
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/pspnet_unet_s5-d16_128x128_40k_chase_db1/pspnet_unet_s5-d16_128x128_40k_chase_db1_20201227_181818-68d4e609.pth
    Config: configs/unet-s5-d16/pspnet_unet_s5-d16_128x128_40k_chase_db1.py



  - Name: deeplabv3_unet_s5-d16_128x128_40k_chase_db1
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: CHASE_DB1
        Metrics:
          mIoU: 0.999
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/deeplabv3_unet_s5-d16_128x128_40k_chase_db1/deeplabv3_unet_s5-d16_128x128_40k_chase_db1_20201226_094047-4c5aefa3.pth
    Config: configs/unet-s5-d16/deeplabv3_unet_s5-d16_128x128_40k_chase_db1.py



  - Name: fcn_unet_s5-d16_256x256_40k_hrf
    In Collection: FCN
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: HRF
        Metrics:
          mIoU: 2.525
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_256x256_40k_hrf/fcn_unet_s5-d16_256x256_40k_hrf_20201223_173724-df3ec8c4.pth
    Config: configs/unet-s5-d16/fcn_unet_s5-d16_256x256_40k_hrf.py



  - Name: pspnet_unet_s5-d16_256x256_40k_hrf
    In Collection: PSPNet
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: HRF
        Metrics:
          mIoU: 2.588
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/pspnet_unet_s5-d16_256x256_40k_hrf/pspnet_unet_s5-d16_256x256_40k_hrf_20201227_181818-fdb7e29b.pth
    Config: configs/unet-s5-d16/pspnet_unet_s5-d16_256x256_40k_hrf.py



  - Name: deeplabv3_unet_s5-d16_256x256_40k_hrf
    In Collection: DeepLabV3
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: HRF
        Metrics:
          mIoU: 2.604
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/unet/deeplabv3_unet_s5-d16_256x256_40k_hrf/deeplabv3_unet_s5-d16_256x256_40k_hrf_20201226_094047-3a1fdf85.pth
    Config: configs/unet-s5-d16/deeplabv3_unet_s5-d16_256x256_40k_hrf.py
