Collections:
- Name: ISANet
  Metadata:
    Training Data:
    - Cityscapes
    - ADE20K
    - Pascal VOC 2012 + Aug
  Paper:
    URL: https://arxiv.org/abs/1907.12273
    Title: Interlaced Sparse Self-Attention for Semantic Segmentation
  README: configs/isanet/README.md
  Code:
    URL: https://github.com/open-mmlab/mmsegmentation/blob/v0.18.0/mmseg/models/decode_heads/isa_head.py#L58
    Version: v0.18.0
  Converted From:
    Code: https://github.com/openseg-group/openseg.pytorch
Models:
- Name: isanet_r50-d8_4xb2-40k_cityscapes-512x1024
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (512,1024)
    lr schd: 40000
    inference time (ms/im):
    - value: 343.64
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    Training Memory (GB): 5.869
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.49
      mIoU(ms+flip): 79.44
  Config: configs/isanet/isanet_r50-d8_4xb2-40k_cityscapes-512x1024.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_512x1024_40k_cityscapes/isanet_r50-d8_512x1024_40k_cityscapes_20210901_054739-981bd763.pth
- Name: isanet_r50-d8_4xb2-80k_cityscapes-512x1024
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (512,1024)
    lr schd: 80000
    inference time (ms/im):
    - value: 343.64
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    Training Memory (GB): 5.869
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.68
      mIoU(ms+flip): 80.25
  Config: configs/isanet/isanet_r50-d8_4xb2-80k_cityscapes-512x1024.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_512x1024_80k_cityscapes/isanet_r50-d8_512x1024_80k_cityscapes_20210901_074202-89384497.pth
- Name: isanet_r50-d8_4xb2-40k_cityscapes-769x769
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (769,769)
    lr schd: 40000
    inference time (ms/im):
    - value: 649.35
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (769,769)
    Training Memory (GB): 6.759
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.7
      mIoU(ms+flip): 80.28
  Config: configs/isanet/isanet_r50-d8_4xb2-40k_cityscapes-769x769.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_769x769_40k_cityscapes/isanet_r50-d8_769x769_40k_cityscapes_20210903_050200-4ae7e65b.pth
- Name: isanet_r50-d8_4xb2-80k_cityscapes-769x769
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (769,769)
    lr schd: 80000
    inference time (ms/im):
    - value: 649.35
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (769,769)
    Training Memory (GB): 6.759
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.29
      mIoU(ms+flip): 80.53
  Config: configs/isanet/isanet_r50-d8_4xb2-80k_cityscapes-769x769.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_769x769_80k_cityscapes/isanet_r50-d8_769x769_80k_cityscapes_20210903_101126-99b54519.pth
- Name: isanet_r101-d8_4xb2-40k_cityscapes-512x1024
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 40000
    inference time (ms/im):
    - value: 425.53
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    Training Memory (GB): 9.425
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.58
      mIoU(ms+flip): 81.05
  Config: configs/isanet/isanet_r101-d8_4xb2-40k_cityscapes-512x1024.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_512x1024_40k_cityscapes/isanet_r101-d8_512x1024_40k_cityscapes_20210901_145553-293e6bd6.pth
- Name: isanet_r101-d8_4xb2-80k_cityscapes-512x1024
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
    inference time (ms/im):
    - value: 425.53
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    Training Memory (GB): 9.425
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.32
      mIoU(ms+flip): 81.58
  Config: configs/isanet/isanet_r101-d8_4xb2-80k_cityscapes-512x1024.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_512x1024_80k_cityscapes/isanet_r101-d8_512x1024_80k_cityscapes_20210901_145243-5b99c9b2.pth
- Name: isanet_r101-d8_4xb2-40k_cityscapes-769x769
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (769,769)
    lr schd: 40000
    inference time (ms/im):
    - value: 1086.96
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (769,769)
    Training Memory (GB): 10.815
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.68
      mIoU(ms+flip): 80.95
  Config: configs/isanet/isanet_r101-d8_4xb2-40k_cityscapes-769x769.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_769x769_40k_cityscapes/isanet_r101-d8_769x769_40k_cityscapes_20210903_111320-509e7224.pth
- Name: isanet_r101-d8_4xb2-80k_cityscapes-769x769
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (769,769)
    lr schd: 80000
    inference time (ms/im):
    - value: 1086.96
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (769,769)
    Training Memory (GB): 10.815
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.61
      mIoU(ms+flip): 81.59
  Config: configs/isanet/isanet_r101-d8_4xb2-80k_cityscapes-769x769.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_769x769_80k_cityscapes/isanet_r101-d8_769x769_80k_cityscapes_20210903_111319-24f71dfa.pth
- Name: isanet_r50-d8_4xb4-80k_ade20k-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 80000
    inference time (ms/im):
    - value: 44.35
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 9.0
  Results:
  - Task: Semantic Segmentation
    Dataset: ADE20K
    Metrics:
      mIoU: 41.12
      mIoU(ms+flip): 42.35
  Config: configs/isanet/isanet_r50-d8_4xb4-80k_ade20k-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_512x512_80k_ade20k/isanet_r50-d8_512x512_80k_ade20k_20210903_124557-6ed83a0c.pth
- Name: isanet_r50-d8_4xb4-160k_ade20k-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 160000
    inference time (ms/im):
    - value: 44.35
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 9.0
  Results:
  - Task: Semantic Segmentation
    Dataset: ADE20K
    Metrics:
      mIoU: 42.59
      mIoU(ms+flip): 43.07
  Config: configs/isanet/isanet_r50-d8_4xb4-160k_ade20k-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_512x512_160k_ade20k/isanet_r50-d8_512x512_160k_ade20k_20210903_104850-f752d0a3.pth
- Name: isanet_r101-d8_4xb4-80k_ade20k-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 80000
    inference time (ms/im):
    - value: 94.7
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 12.562
  Results:
  - Task: Semantic Segmentation
    Dataset: ADE20K
    Metrics:
      mIoU: 43.51
      mIoU(ms+flip): 44.38
  Config: configs/isanet/isanet_r101-d8_4xb4-80k_ade20k-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_512x512_80k_ade20k/isanet_r101-d8_512x512_80k_ade20k_20210903_162056-68b235c2.pth
- Name: isanet_r101-d8_4xb4-160k_ade20k-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 160000
    inference time (ms/im):
    - value: 94.7
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 12.562
  Results:
  - Task: Semantic Segmentation
    Dataset: ADE20K
    Metrics:
      mIoU: 43.8
      mIoU(ms+flip): 45.4
  Config: configs/isanet/isanet_r101-d8_4xb4-160k_ade20k-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_512x512_160k_ade20k/isanet_r101-d8_512x512_160k_ade20k_20210903_211431-a7879dcd.pth
- Name: isanet_r50-d8_4xb4-20k_voc12aug-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 20000
    inference time (ms/im):
    - value: 43.33
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 5.9
  Results:
  - Task: Semantic Segmentation
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 76.78
      mIoU(ms+flip): 77.79
  Config: configs/isanet/isanet_r50-d8_4xb4-20k_voc12aug-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_512x512_20k_voc12aug/isanet_r50-d8_512x512_20k_voc12aug_20210901_164838-79d59b80.pth
- Name: isanet_r50-d8_4xb4-40k_voc12aug-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 40000
    inference time (ms/im):
    - value: 43.33
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 5.9
  Results:
  - Task: Semantic Segmentation
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 76.2
      mIoU(ms+flip): 77.22
  Config: configs/isanet/isanet_r50-d8_4xb4-40k_voc12aug-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r50-d8_512x512_40k_voc12aug/isanet_r50-d8_512x512_40k_voc12aug_20210901_151349-7d08a54e.pth
- Name: isanet_r101-d8_4xb4-20k_voc12aug-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 20000
    inference time (ms/im):
    - value: 134.77
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 9.465
  Results:
  - Task: Semantic Segmentation
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 78.46
      mIoU(ms+flip): 79.16
  Config: configs/isanet/isanet_r101-d8_4xb4-20k_voc12aug-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_512x512_20k_voc12aug/isanet_r101-d8_512x512_20k_voc12aug_20210901_115805-3ccbf355.pth
- Name: isanet_r101-d8_4xb4-40k_voc12aug-512x512
  In Collection: ISANet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 40000
    inference time (ms/im):
    - value: 134.77
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,512)
    Training Memory (GB): 9.465
  Results:
  - Task: Semantic Segmentation
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 78.12
      mIoU(ms+flip): 79.04
  Config: configs/isanet/isanet_r101-d8_4xb4-40k_voc12aug-512x512.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/isanet/isanet_r101-d8_512x512_40k_voc12aug/isanet_r101-d8_512x512_40k_voc12aug_20210901_145814-bc71233b.pth
