Models:
  - Name: fcn_hr18s_512x1024_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 23.74
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 73.86
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x1024_40k_cityscapes/fcn_hr18s_512x1024_40k_cityscapes_20200601_014216-93db27d0.pth
    Config: configs/fcn/fcn_hr18s_512x1024_40k_cityscapes.py



  - Name: fcn_hr18_512x1024_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 12.97
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.19
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x1024_40k_cityscapes/fcn_hr18_512x1024_40k_cityscapes_20200601_014216-f196fb4e.pth
    Config: configs/fcn/fcn_hr18_512x1024_40k_cityscapes.py



  - Name: fcn_hr48_512x1024_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 6.42
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.48
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x1024_40k_cityscapes/fcn_hr48_512x1024_40k_cityscapes_20200601_014240-a989b146.pth
    Config: configs/fcn/fcn_hr48_512x1024_40k_cityscapes.py



  - Name: fcn_hr18s_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 23.74
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.31
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x1024_80k_cityscapes/fcn_hr18s_512x1024_80k_cityscapes_20200601_202700-1462b75d.pth
    Config: configs/fcn/fcn_hr18s_512x1024_80k_cityscapes.py



  - Name: fcn_hr18_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 12.97
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.65
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x1024_80k_cityscapes/fcn_hr18_512x1024_80k_cityscapes_20200601_223255-4e7b345e.pth
    Config: configs/fcn/fcn_hr18_512x1024_80k_cityscapes.py



  - Name: fcn_hr48_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 6.42
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 79.93
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x1024_80k_cityscapes/fcn_hr48_512x1024_80k_cityscapes_20200601_202606-58ea95d6.pth
    Config: configs/fcn/fcn_hr48_512x1024_80k_cityscapes.py



  - Name: fcn_hr18s_512x1024_160k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 23.74
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.31
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x1024_160k_cityscapes/fcn_hr18s_512x1024_160k_cityscapes_20200602_190901-4a0797ea.pth
    Config: configs/fcn/fcn_hr18s_512x1024_160k_cityscapes.py



  - Name: fcn_hr18_512x1024_160k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 12.97
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.80
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x1024_160k_cityscapes/fcn_hr18_512x1024_160k_cityscapes_20200602_190822-221e4a4f.pth
    Config: configs/fcn/fcn_hr18_512x1024_160k_cityscapes.py



  - Name: fcn_hr48_512x1024_160k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (fps): 6.42
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 80.65
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x1024_160k_cityscapes/fcn_hr48_512x1024_160k_cityscapes_20200602_190946-59b7973e.pth
    Config: configs/fcn/fcn_hr48_512x1024_160k_cityscapes.py



  - Name: fcn_hr18s_512x512_80k_ade20k
    In Collection: FCN
    Metadata:
      inference time (fps): 38.66
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 31.38
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x512_80k_ade20k/fcn_hr18s_512x512_80k_ade20k_20200614_144345-77fc814a.pth
    Config: configs/fcn/fcn_hr18s_512x512_80k_ade20k.py



  - Name: fcn_hr18_512x512_80k_ade20k
    In Collection: FCN
    Metadata:
      inference time (fps): 22.57
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 35.51
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x512_80k_ade20k/fcn_hr18_512x512_80k_ade20k_20200614_185145-66f20cb7.pth
    Config: configs/fcn/fcn_hr18_512x512_80k_ade20k.py



  - Name: fcn_hr48_512x512_80k_ade20k
    In Collection: FCN
    Metadata:
      inference time (fps): 21.23
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 41.90
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x512_80k_ade20k/fcn_hr48_512x512_80k_ade20k_20200614_193946-7ba5258d.pth
    Config: configs/fcn/fcn_hr48_512x512_80k_ade20k.py



  - Name: fcn_hr18s_512x512_160k_ade20k
    In Collection: FCN
    Metadata:
      inference time (fps): 38.66
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 33.00
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x512_160k_ade20k/fcn_hr18s_512x512_160k_ade20k_20200614_214413-870f65ac.pth
    Config: configs/fcn/fcn_hr18s_512x512_160k_ade20k.py



  - Name: fcn_hr18_512x512_160k_ade20k
    In Collection: FCN
    Metadata:
      inference time (fps): 22.57
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 36.79
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x512_160k_ade20k/fcn_hr18_512x512_160k_ade20k_20200614_214426-ca961836.pth
    Config: configs/fcn/fcn_hr18_512x512_160k_ade20k.py



  - Name: fcn_hr48_512x512_160k_ade20k
    In Collection: FCN
    Metadata:
      inference time (fps): 21.23
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 42.02
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x512_160k_ade20k/fcn_hr48_512x512_160k_ade20k_20200614_214407-a52fc02c.pth
    Config: configs/fcn/fcn_hr48_512x512_160k_ade20k.py



  - Name: fcn_hr18s_512x512_20k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (fps): 43.36
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 65.20
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x512_20k_voc12aug/fcn_hr18s_512x512_20k_voc12aug_20200617_224503-56e36088.pth
    Config: configs/fcn/fcn_hr18s_512x512_20k_voc12aug.py



  - Name: fcn_hr18_512x512_20k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (fps): 23.48
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 72.30
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x512_20k_voc12aug/fcn_hr18_512x512_20k_voc12aug_20200617_224503-488d45f7.pth
    Config: configs/fcn/fcn_hr18_512x512_20k_voc12aug.py



  - Name: fcn_hr48_512x512_20k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (fps): 22.05
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 75.87
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x512_20k_voc12aug/fcn_hr48_512x512_20k_voc12aug_20200617_224419-89de05cd.pth
    Config: configs/fcn/fcn_hr48_512x512_20k_voc12aug.py



  - Name: fcn_hr18s_512x512_40k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (fps): 43.36
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 66.61
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18s_512x512_40k_voc12aug/fcn_hr18s_512x512_40k_voc12aug_20200614_000648-4f8d6e7f.pth
    Config: configs/fcn/fcn_hr18s_512x512_40k_voc12aug.py



  - Name: fcn_hr18_512x512_40k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (fps): 23.48
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 72.90
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr18_512x512_40k_voc12aug/fcn_hr18_512x512_40k_voc12aug_20200613_224401-1b4b76cd.pth
    Config: configs/fcn/fcn_hr18_512x512_40k_voc12aug.py



  - Name: fcn_hr48_512x512_40k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (fps): 22.05
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 76.24
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_512x512_40k_voc12aug/fcn_hr48_512x512_40k_voc12aug_20200613_222111-1b0f18bc.pth
    Config: configs/fcn/fcn_hr48_512x512_40k_voc12aug.py



  - Name: fcn_hr48_480x480_40k_pascal_context
    In Collection: FCN
    Metadata:
      inference time (fps): 8.86
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 45.14
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_480x480_40k_pascal_context/fcn_hr48_480x480_40k_pascal_context_20200911_164852-667d00b0.pth
    Config: configs/fcn/fcn_hr48_480x480_40k_pascal_context.py



  - Name: fcn_hr48_480x480_80k_pascal_context
    In Collection: FCN
    Metadata:
      inference time (fps): 8.86
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 45.84
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_480x480_80k_pascal_context/fcn_hr48_480x480_80k_pascal_context_20200911_155322-847a6711.pth
    Config: configs/fcn/fcn_hr48_480x480_80k_pascal_context.py



  - Name: fcn_hr48_480x480_40k_pascal_context_59
    In Collection: FCN
    Metadata:
      inference time (fps): None
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 50.33
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_480x480_40k_pascal_context_59/fcn_hr48_480x480_40k_pascal_context_59_20210410_122738-b808b8b2.pth
    Config: configs/fcn/fcn_hr48_480x480_40k_pascal_context_59.py



  - Name: fcn_hr48_480x480_80k_pascal_context
    In Collection: FCN
    Metadata:
      inference time (fps): None
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 51.12
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/hrnet/fcn_hr48_480x480_80k_pascal_context_59/fcn_hr48_480x480_80k_pascal_context_59_20210411_003240-3ae7081e.pth
    Config: configs/fcn/fcn_hr48_480x480_80k_pascal_context.py
