Collections:
  - Name: FCN
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal Context
        - Pascal VOC 2012 + Aug
        - ADE20K
  - Name: FCN-D6
    Metadata:
      Training Data:
        - Cityscapes
        - Pascal Context
        - Pascal VOC 2012 + Aug
        - ADE20K

Models:

  - Name: fcn_r50-d8_512x1024_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 239.81
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 72.25
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_512x1024_40k_cityscapes/fcn_r50-d8_512x1024_40k_cityscapes_20200604_192608-efe53f0d.pth
    Config: configs/fcn/fcn_r50-d8_512x1024_40k_cityscapes.py



  - Name: fcn_r101-d8_512x1024_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 375.94
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.45
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_512x1024_40k_cityscapes/fcn_r101-d8_512x1024_40k_cityscapes_20200604_181852-a883d3a1.pth
    Config: configs/fcn/fcn_r101-d8_512x1024_40k_cityscapes.py



  - Name: fcn_r50-d8_769x769_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 555.56
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 71.47
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_769x769_40k_cityscapes/fcn_r50-d8_769x769_40k_cityscapes_20200606_113104-977b5d02.pth
    Config: configs/fcn/fcn_r50-d8_769x769_40k_cityscapes.py



  - Name: fcn_r101-d8_769x769_40k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 840.34
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 73.93
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_769x769_40k_cityscapes/fcn_r101-d8_769x769_40k_cityscapes_20200606_113208-7d4ab69c.pth
    Config: configs/fcn/fcn_r101-d8_769x769_40k_cityscapes.py



  - Name: fcn_r18-d8_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 68.26
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 71.11
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r18-d8_512x1024_80k_cityscapes/fcn_r18-d8_512x1024_80k_cityscapes_20201225_021327-6c50f8b4.pth
    Config: configs/fcn/fcn_r18-d8_512x1024_80k_cityscapes.py



  - Name: fcn_r50-d8_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 239.81
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 73.61
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_512x1024_80k_cityscapes/fcn_r50-d8_512x1024_80k_cityscapes_20200606_113019-03aa804d.pth
    Config: configs/fcn/fcn_r50-d8_512x1024_80k_cityscapes.py



  - Name: fcn_r101-d8_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 375.94
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.13
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_512x1024_80k_cityscapes/fcn_r101-d8_512x1024_80k_cityscapes_20200606_113038-3fb937eb.pth
    Config: configs/fcn/fcn_r101-d8_512x1024_80k_cityscapes.py



  - Name: fcn_r18-d8_769x769_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 156.25
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 70.80
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r18-d8_769x769_80k_cityscapes/fcn_r18-d8_769x769_80k_cityscapes_20201225_021451-9739d1b8.pth
    Config: configs/fcn/fcn_r18-d8_769x769_80k_cityscapes.py



  - Name: fcn_r50-d8_769x769_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 555.56
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 72.64
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_769x769_80k_cityscapes/fcn_r50-d8_769x769_80k_cityscapes_20200606_195749-f5caeabc.pth
    Config: configs/fcn/fcn_r50-d8_769x769_80k_cityscapes.py



  - Name: fcn_r101-d8_769x769_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 840.34
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.52
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_769x769_80k_cityscapes/fcn_r101-d8_769x769_80k_cityscapes_20200606_214354-45cbac68.pth
    Config: configs/fcn/fcn_r101-d8_769x769_80k_cityscapes.py



  - Name: fcn_r18b-d8_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 59.74
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 70.24
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r18b-d8_512x1024_80k_cityscapes/fcn_r18b-d8_512x1024_80k_cityscapes_20201225_230143-92c0f445.pth
    Config: configs/fcn/fcn_r18b-d8_512x1024_80k_cityscapes.py



  - Name: fcn_r50b-d8_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 238.1
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.65
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50b-d8_512x1024_80k_cityscapes/fcn_r50b-d8_512x1024_80k_cityscapes_20201225_094221-82957416.pth
    Config: configs/fcn/fcn_r50b-d8_512x1024_80k_cityscapes.py



  - Name: fcn_r101b-d8_512x1024_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 366.3
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.37
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101b-d8_512x1024_80k_cityscapes/fcn_r101b-d8_512x1024_80k_cityscapes_20201226_160213-4543858f.pth
    Config: configs/fcn/fcn_r101b-d8_512x1024_80k_cityscapes.py



  - Name: fcn_r18b-d8_769x769_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 149.25
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 69.66
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r18b-d8_769x769_80k_cityscapes/fcn_r18b-d8_769x769_80k_cityscapes_20201226_004430-32d504e5.pth
    Config: configs/fcn/fcn_r18b-d8_769x769_80k_cityscapes.py



  - Name: fcn_r50b-d8_769x769_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 549.45
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 73.83
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50b-d8_769x769_80k_cityscapes/fcn_r50b-d8_769x769_80k_cityscapes_20201225_094223-94552d38.pth
    Config: configs/fcn/fcn_r50b-d8_769x769_80k_cityscapes.py



  - Name: fcn_r101b-d8_769x769_80k_cityscapes
    In Collection: FCN
    Metadata:
      inference time (ms/im): 869.57
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.02
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101b-d8_769x769_80k_cityscapes/fcn_r101b-d8_769x769_80k_cityscapes_20201226_170012-82be37e2.pth
    Config: configs/fcn/fcn_r101b-d8_769x769_80k_cityscapes.py



  - Name: fcn_d6_r50-d16_512x1024_40k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 97.85
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.06
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r50-d16_512x1024_40k_cityscapes/fcn_d6_r50-d16_512x1024_40k_cityscapes-98d5d1bc.pth
    Config: configs/fcn-d6/fcn_d6_r50-d16_512x1024_40k_cityscapes.py



  - Name: fcn_d6_r50-d16_512x1024_80k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 96.62
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.27
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r50-d16_512x1024_80k_cityscapes/fcn_d6_r50-d16_512x1024_40k_cityscapes-98d5d1bc.pth
    Config: configs/fcn-d6/fcn_d6_r50-d16_512x1024_80k_cityscapes.py



  - Name: fcn_d6_r50-d16_769x769_40k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 239.81
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.82
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r50-d16_769x769_40k_cityscapes/fcn_d6_r50-d16_769x769_40k_cityscapes-1aab18ed.pth
    Config: configs/fcn-d6/fcn_d6_r50-d16_769x769_40k_cityscapes.py



  - Name: fcn_d6_r50-d16_769x769_80k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 240.96
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.04
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r50-d16_769x769_80k_cityscapes/fcn_d6_r50-d16_769x769_80k_cityscapes-109d88eb.pth
    Config: configs/fcn-d6/fcn_d6_r50-d16_769x769_80k_cityscapes.py



  - Name: fcn_d6_r101-d16_512x1024_40k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 124.38
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.36
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r101-d16_512x1024_40k_cityscapes/fcn_d6_r101-d16_512x1024_40k_cityscapes-9cf2b450.pth
    Config: configs/fcn-d6/fcn_d6_r101-d16_512x1024_40k_cityscapes.py



  - Name: fcn_d6_r101-d16_512x1024_80k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 121.07
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.46
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r101-d16_512x1024_80k_cityscapes/fcn_d6_r101-d16_512x1024_80k_cityscapes-cb336445.pth
    Config: configs/fcn-d6/fcn_d6_r101-d16_512x1024_80k_cityscapes.py



  - Name: fcn_d6_r101-d16_769x769_40k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 320.51
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 77.28
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r101-d16_769x769_40k_cityscapes/fcn_d6_r101-d16_769x769_40k_cityscapes-60b114e9.pth
    Config: configs/fcn-d6/fcn_d6_r101-d16_769x769_40k_cityscapes.py



  - Name: fcn_d6_r101-d16_769x769_80k_cityscapes
    In Collection: FCN-D6
    Metadata:
      inference time (ms/im): 311.53
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.06
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_d6_r101-d16_769x769_80k_cityscapes/fcn_d6_r101-d16_769x769_80k_cityscapes-e33adc4f.pth
    Config: configs/fcn-d6/fcn_d6_r101-d16_769x769_80k_cityscapes.py



  - Name: fcn_r50-d8_512x512_80k_ade20k
    In Collection: FCN
    Metadata:
      inference time (ms/im): 42.57
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 35.94
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_512x512_80k_ade20k/fcn_r50-d8_512x512_80k_ade20k_20200614_144016-f8ac5082.pth
    Config: configs/fcn/fcn_r50-d8_512x512_80k_ade20k.py



  - Name: fcn_r101-d8_512x512_80k_ade20k
    In Collection: FCN
    Metadata:
      inference time (ms/im): 67.66
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 39.61
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_512x512_80k_ade20k/fcn_r101-d8_512x512_80k_ade20k_20200615_014143-bc1809f7.pth
    Config: configs/fcn/fcn_r101-d8_512x512_80k_ade20k.py



  - Name: fcn_r50-d8_512x512_160k_ade20k
    In Collection: FCN
    Metadata:
      inference time (ms/im): 42.57
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 36.10
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_512x512_160k_ade20k/fcn_r50-d8_512x512_160k_ade20k_20200615_100713-4edbc3b4.pth
    Config: configs/fcn/fcn_r50-d8_512x512_160k_ade20k.py



  - Name: fcn_r101-d8_512x512_160k_ade20k
    In Collection: FCN
    Metadata:
      inference time (ms/im): 67.66
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 39.91
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_512x512_160k_ade20k/fcn_r101-d8_512x512_160k_ade20k_20200615_105816-fd192bd5.pth
    Config: configs/fcn/fcn_r101-d8_512x512_160k_ade20k.py



  - Name: fcn_r50-d8_512x512_20k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (ms/im): 42.96
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 67.08
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_512x512_20k_voc12aug/fcn_r50-d8_512x512_20k_voc12aug_20200617_010715-52dc5306.pth
    Config: configs/fcn/fcn_r50-d8_512x512_20k_voc12aug.py



  - Name: fcn_r101-d8_512x512_20k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (ms/im): 67.52
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 71.16
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_512x512_20k_voc12aug/fcn_r101-d8_512x512_20k_voc12aug_20200617_010842-0bb4e798.pth
    Config: configs/fcn/fcn_r101-d8_512x512_20k_voc12aug.py



  - Name: fcn_r50-d8_512x512_40k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (ms/im): 42.96
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 66.97
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r50-d8_512x512_40k_voc12aug/fcn_r50-d8_512x512_40k_voc12aug_20200613_161222-5e2dbf40.pth
    Config: configs/fcn/fcn_r50-d8_512x512_40k_voc12aug.py



  - Name: fcn_r101-d8_512x512_40k_voc12aug
    In Collection: FCN
    Metadata:
      inference time (ms/im): 67.52
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal VOC 2012 + Aug
        Metrics:
          mIoU: 69.91
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_512x512_40k_voc12aug/fcn_r101-d8_512x512_40k_voc12aug_20200613_161240-4c8bcefd.pth
    Config: configs/fcn/fcn_r101-d8_512x512_40k_voc12aug.py



  - Name: fcn_r101-d8_480x480_40k_pascal_context
    In Collection: FCN
    Metadata:
      inference time (ms/im): 100.7
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 44.43
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_480x480_40k_pascal_context/fcn_r101-d8_480x480_40k_pascal_context-20210421_154757-b5e97937.pth
    Config: configs/fcn/fcn_r101-d8_480x480_40k_pascal_context.py



  - Name: fcn_r101-d8_480x480_80k_pascal_context
    In Collection: FCN
    Metadata:
      inference time (ms/im): 100.7
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 44.13
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_480x480_80k_pascal_context/fcn_r101-d8_480x480_80k_pascal_context-20210421_163310-4711813f.pth
    Config: configs/fcn/fcn_r101-d8_480x480_80k_pascal_context.py



  - Name: fcn_r101-d8_480x480_40k_pascal_context_59
    In Collection: FCN
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 48.42
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_480x480_40k_pascal_context_59/fcn_r101-d8_480x480_40k_pascal_context_59_20210415_230724-8cf83682.pth
    Config: configs/fcn/fcn_r101-d8_480x480_40k_pascal_context_59.py



  - Name: fcn_r101-d8_480x480_80k_pascal_context_59
    In Collection: FCN
    Metadata:
      inference time (ms/im): None
    Results:
      - Task: Semantic Segmentation
        Dataset: Pascal Context
        Metrics:
          mIoU: 49.35
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fcn/fcn_r101-d8_480x480_80k_pascal_context_59/fcn_r101-d8_480x480_80k_pascal_context_59_20210416_110804-9a6f2c94.pth
    Config: configs/fcn/fcn_r101-d8_480x480_80k_pascal_context_59.py
