Collections:
  - Name: PointRend
    Metadata:
      Training Data:
        - Cityscapes
        - ADE20K

Models:

  - Name: pointrend_r50_512x1024_80k_cityscapes
    In Collection: PointRend
    Metadata:
      inference time (ms/im): 117.92
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 76.47
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/point_rend/pointrend_r50_512x1024_80k_cityscapes/pointrend_r50_512x1024_80k_cityscapes_20200711_015821-bb1ff523.pth
    Config: configs/pointrend/pointrend_r50_512x1024_80k_cityscapes.py



  - Name: pointrend_r101_512x1024_80k_cityscapes
    In Collection: PointRend
    Metadata:
      inference time (ms/im): 142.86
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 78.30
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/point_rend/pointrend_r101_512x1024_80k_cityscapes/pointrend_r101_512x1024_80k_cityscapes_20200711_170850-d0ca84be.pth
    Config: configs/pointrend/pointrend_r101_512x1024_80k_cityscapes.py



  - Name: pointrend_r50_512x512_160k_ade20k
    In Collection: PointRend
    Metadata:
      inference time (ms/im): 57.77
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 37.64
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/point_rend/pointrend_r50_512x512_160k_ade20k/pointrend_r50_512x512_160k_ade20k_20200807_232644-ac3febf2.pth
    Config: configs/pointrend/pointrend_r50_512x512_160k_ade20k.py



  - Name: pointrend_r101_512x512_160k_ade20k
    In Collection: PointRend
    Metadata:
      inference time (ms/im): 64.52
    Results:
      - Task: Semantic Segmentation
        Dataset: ADE20K
        Metrics:
          mIoU: 40.02
    Weights: https://download.openmmlab.com/mmsegmentation/v0.5/point_rend/pointrend_r101_512x512_160k_ade20k/pointrend_r101_512x512_160k_ade20k_20200808_030852-8834902a.pth
    Config: configs/pointrend/pointrend_r101_512x512_160k_ade20k.py
